# Generated by Django 5.1.7 on 2025-06-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Nome comercial.', max_length=255, null=True)),
                ('cnpj', models.CharField(help_text='CNPJ no formato XX.XXX.XXX/XXXX-XX.', max_length=18, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(help_text='Sigla do estado (SC).', max_length=2)),
                ('cep', models.CharField(help_text='CEP no formato XXXXX-XXX/XXXXX-XXX.', max_length=9)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('nome_contato', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='inscricao_estadual',
        ),
    ]
