# Generated by Django 5.1.7 on 2025-09-18 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cargo_categoria_cliente_compra_estoque_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='usuario',
        ),
        migrations.AddField(
            model_name='venda',
            name='funcionario',
            field=models.ForeignKey(default=1, help_text='Funcionário que realizou a venda.', on_delete=django.db.models.deletion.CASCADE, to='core.funcionario'),
            preserve_default=False,
        ),
    ]
