# Generated by Django 5.1.7 on 2025-09-19 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_venda_usuario_venda_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorioestoque',
            name='usuario_gerador',
        ),
        migrations.RemoveField(
            model_name='relatoriovenda',
            name='usuario_gerador',
        ),
        migrations.AddField(
            model_name='relatorioestoque',
            name='funcionario_gerador',
            field=models.ForeignKey(default=1, help_text='Funcionário que gerou o relatório.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relatoriovenda',
            name='funcionario_gerador',
            field=models.ForeignKey(default=1, help_text='Funcionário que gerou o relatório.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
