# Generated by Django 5.1.7 on 2025-09-19 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_relatorioestoque_usuario_gerador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorioestoque',
            name='funcionario_gerador',
            field=models.ForeignKey(help_text='Funcionário que gerou o relatório.', on_delete=django.db.models.deletion.PROTECT, to='core.funcionario'),
        ),
        migrations.AlterField(
            model_name='relatoriovenda',
            name='funcionario_gerador',
            field=models.ForeignKey(help_text='Funcionário que gerou o relatório.', on_delete=django.db.models.deletion.PROTECT, to='core.funcionario'),
        ),
    ]
