# Generated by Django 5.1.7 on 2025-09-19 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_movimentacaoestoque_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='usuario',
        ),
        migrations.AddField(
            model_name='compra',
            name='funcionario',
            field=models.ForeignKey(default=1, help_text='Funcionário responsável pela compra.', on_delete=django.db.models.deletion.PROTECT, to='core.funcionario'),
            preserve_default=False,
        ),
    ]
